#!/bin/bash

all:
	@echo "CC main.cpp"
	@-g++ main.cpp -lopencv_core -lopencv_imgproc -lopencv_calib3d -lopencv_video -lopencv_features2d -lopencv_ml -lopencv_highgui -lopencv_objdetect -lopencv_contrib -lopencv_legacy

clean:
	@-rm a.out
