#!/usr/bin/env bash

cp output5 ../../libsvm/output
cp input5 ../../libsvm/input

cd ../../libsvm/

echo "Scaling data..."

./svm-scale output > output.scale
./svm-scale input > input.scale 

cp output.scale ../aks/nkerns/testnums
cp input.scale ../aks/predict/input 

cd ../aks/nkerns
head -6000 testnums > input

echo "Training Models..."

./main input -c 100

cp input.model ../predict/
cd ../predict/

echo "Testing accuracy..."

./main input input.model /dev/null
