#!/usr/bin/env python

fin = open('data','r')

width = 640
height = 480

for line in fin:
	
	output = []
	parts = line.split(" ")
	parts[2] = parts[2].strip()

	if(int(parts[0]) == 2):
		parts[0] = "-1";

	part1 = parts[1].split(":")
	part2 = parts[2].split(":")

	print parts[0] + " " + \
			str((width / 2) - int(float(part1[1]) * width)) + " " + \
			str((height / 2) - int(float(part2[1]) * height))
