#!/usr/bin/env python

CLOCK_INDEX = 11


f = open("exampleData.csv")

for line in f:
	
	cols = line.split(",")

	if int(cols[33]) > 0:
		print "1",
	else:
		print "2",

	for i in range(1,29):

		if i == CLOCK_INDEX:
			print str(i) + ":" + str(int(cols[i].split(":")[0])),
		else:
			print str(i) + ":" + cols[i],

	print " "
