#!/usr/bin/env python

import random

f = open("data")

for line in f:
	
	parts = line.split(" ")
	parts[2] = parts[2].strip()

	cls = int(parts[0])

	if cls is 1:
		print "+1 ",
	else:
		print "-1 ",

	print parts[1].split(":")[1] + " " + parts[2].split(":")[1]
