#!/usr/bin/env python

import random

f = open("data")

cnt1 = 0.0
cnt2 = 0.0

sum1x = 0.0
sum2x = 0.0
sum1y = 0.0
sum2y = 0.0

avg1x = 0.0
avg2x = 0.0
avg1y = 0.0
avg2y = 0.0

for line in f:
	
	parts = line.split(" ")
	parts[2] = parts[2].strip()

	cls = int(parts[0])

	if cls is 1:
		cnt1 += 1.0
		sum1x += float(parts[1].split(":")[1])
		sum1y += float(parts[2].split(":")[1])
	elif cls is 2:
		cnt2 += 1.0
		sum2x += float(parts[1].split(":")[1])
		sum2y += float(parts[2].split(":")[1])

avg1x = sum1x / cnt1
avg2x = sum2x / cnt2
avg1y = sum1y / cnt1
avg2y = sum2y / cnt2

print "class 1 average: (" + str(avg1x) + "," + str(avg1y) + ")"
print "class 2 average: (" + str(avg2x) + "," + str(avg2y) + ")"
