#!/usr/bin/env bash

cd ..

# Add bin to path

export PATH=$PWD/bin:$PATH


# Build SVM if needed

echo "Building SVM..."

cd svm
make &> /dev/null

cp svm-scale   ../bin
cp svm-train   ../bin
cp svm-predict ../bin

cd ..


# Copy vectors for classification

cp mnist/vecs/train datasets/train
cp mnist/vecs/test datasets/test


# Scaling

echo "Scaling data..."

cd datasets

svm-scale train > train.scale
svm-scale test > test.scale


# Training

echo "Training Models..."

svm-train -c 100 -t 1 -d 5 -m 1000 train.scale


# Testing 

echo "Testing accuracy..."

svm-predict test.scale train.scale.model /dev/null


echo "Done."
